const TZ = 'America/Argentina/Buenos_Aires';
const DATA_FALLBACK = {
  source:'safe', updatedAt:new Date().toISOString(),
  sectors:{
    youtube:{title:'YouTube Lab',agent:'Chevy',metrics:{subscribers:2680,totalViews:126321,videos:77,periodViews:119,periodLikes:3,periodComments:1,periodShares:2,topVideo:'LA BRUJA 🔮 Lunes 21 de Septiembre',topVideoViews:85,topRetention:111.2}},
    tiktokMain:{title:'TikTok SebasWit',agent:'Nora',metrics:{followers:1108,totalLikes:17580,videos:21,periodViews:63,periodLikes:5,periodComments:0,periodShares:0,profileViews:1}},
    tiktokDual:{title:'TikTok DUAL / Nexus',agent:'Luca',metrics:{followers:25,totalLikes:206,videos:10,periodViews:1,periodLikes:0,periodComments:0,periodShares:0,profileViews:0}},
    instagram:{title:'Instagram Nexus',agent:'Iris',metrics:{account:'nexus.series.ia',followers:3,mediaCount:2,reach:0,likes:0,comments:0,shares:0,engaged:0}},
    spotify:{title:'Spotify',agent:'Echo',metrics:{connected:false,artist:'SebasWit',followers:null,popularity:null,releases:null}},
    strategy:{title:'Sala de Estrategia',agent:'Atlas',metrics:{}}, publishing:{title:'Publishing',agent:'Luz',metrics:{}}
  }
};
const AGENTS = {
  sebas:{name:'Sebas',role:'Director General',sector:'direction',sprite:'/npc-sebas.png',home:'sebasDesk'},
  facu:{name:'Facu',role:'Coordinación y Centro de Notificaciones',sector:'coordination',sprite:'/npc-facu.png',home:'facuDesk'},
  chevy:{name:'Chevy',role:'YouTube Analytics',sector:'youtube',sprite:'/npc-chevy.png',home:'youtubeA'},
  vera:{name:'Vera',role:'YouTube Contenido',sector:'youtube',sprite:'/npc-vera.png',home:'youtubeB'},
  nora:{name:'Nora',role:'TikTok SebasWit',sector:'tiktokMain',sprite:'/npc-nora.png',home:'tiktokMain'},
  luca:{name:'Luca',role:'TikTok DUAL / Nexus',sector:'tiktokDual',sprite:'/npc-luca.png',home:'tiktokDual'},
  iris:{name:'Iris',role:'Instagram',sector:'instagram',sprite:'/npc-iris.png',home:'instagram'},
  echo:{name:'Echo',role:'Spotify',sector:'spotify',sprite:'/npc-echo.png',home:'spotify'},
  atlas:{name:'Atlas',role:'Estrategia',sector:'strategy',sprite:'/npc-atlas.png',home:'strategy'},
  luz:{name:'Luz',role:'Publishing',sector:'publishing',sprite:'/npc-luz.png',home:'publishing'}
};
const ANCHORS = {
  sebasDesk:{x:34.4,y:17.3},facuDesk:{x:62.1,y:16.5},youtubeA:{x:18.2,y:36.5},youtubeB:{x:22.8,y:36.4},tiktokMain:{x:34.0,y:36.7},tiktokDual:{x:49.2,y:36.8},instagram:{x:61.5,y:36.7},spotify:{x:72.6,y:36.8},strategy:{x:49.5,y:59.2},publishing:{x:67.0,y:59.0},
  meeting1:{x:17.6,y:59.5},meeting2:{x:21.0,y:59.2},meeting3:{x:24.0,y:59.2},meeting4:{x:27.1,y:59.4},
  lunch1:{x:84.4,y:46.6},lunch2:{x:88.0,y:46.6},lunch3:{x:84.5,y:57.1},lunch4:{x:88.2,y:57.1},
  restroom:{x:88.6,y:24.5},lobby:{x:51.8,y:81.8}
};
const ROOM_HOTSPOTS = [
  {key:'direction',label:'Dirección',x:15,y:3,w:30,h:18},{key:'coordination',label:'Coordinación',x:47,y:3,w:28,h:18},{key:'youtube',label:'YouTube Lab',x:11,y:22,w:17,h:21},{key:'tiktokMain',label:'TikTok SebasWit',x:28,y:22,w:14,h:21},{key:'tiktokDual',label:'TikTok DUAL / Nexus',x:42,y:22,w:15,h:21},{key:'instagram',label:'Instagram',x:57,y:22,w:12,h:21},{key:'spotify',label:'Spotify',x:69,y:22,w:12,h:21},{key:'meeting',label:'Sala de reuniones',x:10,y:44,w:23,h:22},{key:'strategy',label:'Sala de Estrategia',x:37,y:44,w:19,h:22},{key:'publishing',label:'Publishing',x:56,y:44,w:19,h:22},{key:'lunch',label:'Comedor / café',x:80,y:27,w:15,h:40},{key:'restroom',label:'Baño',x:83,y:5,w:12,h:20}
];
let data = structuredClone(DATA_FALLBACK), states = {}, prevStates = {}, timer = null;
function el(s){return document.querySelector(s)}function all(s){return [...document.querySelectorAll(s)]}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function fmt(v){return Number(v||0).toLocaleString('es-AR')}
function arNow(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()).reduce((o,p)=>(o[p.type]=p.value,o),{});return{date:`${p.year}-${p.month}-${p.day}`,weekday:p.weekday,h:+p.hour,m:+p.minute,s:+p.second,mins:(+p.hour)*60+(+p.minute)}}
function inRange(m,a,b){return m>=a&&m<b}function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function opsWindow(now){const weekend=now.weekday==='Sat'||now.weekday==='Sun';return weekend?[600,1230]:[540,1320]}
function lunchState(id,m){const slots={chevy:[735,780,'lunch1'],iris:[735,780,'lunch2'],echo:[735,780,'lunch3'],luz:[735,780,'lunch4'],vera:[780,825,'lunch1'],nora:[780,825,'lunch2'],luca:[780,825,'lunch3'],atlas:[780,825,'lunch4'],facu:[825,855,'lunch2'],sebas:[855,885,'lunch1']};const s=slots[id];return s&&inRange(m,s[0],s[1])?{status:'lunch',anchor:s[2],task:'Almorzando'}:null}
function meetingState(id,m,now){const weekday=now.weekday;const rotation=['chevy','nora','luca','iris','echo','luz'][hash(now.date)%6];const meetings=[
  {a:630,b:660,ids:['chevy','vera','atlas'],task:'Revisión de YouTube'},
  {a:670,b:700,ids:['nora','luca','iris','atlas'],task:'Revisión de redes'},
  {a:930,b:975,ids:['facu','atlas',rotation],task:'Reunión de estrategia'},
  {a:1050,b:1080,ids:['sebas','facu'],task:'Resumen a Dirección'},
  {a:1090,b:1110,ids:['facu','atlas','luz'],task:'Plan de publicación'}
];
  for(const mt of meetings){if(inRange(m,mt.a,mt.b)&&mt.ids.includes(id)){const idx=mt.ids.indexOf(id);return{status:'meeting',anchor:['meeting1','meeting2','meeting3','meeting4'][idx]||'meeting1',task:mt.task}}}return null}
function restroomState(id,m,now){if(['sebas','facu'].includes(id))return null;const seed=hash(id+now.date);const b1=585+(seed%110),b2=900+((seed>>3)%140);if(inRange(m,b1,b1+7)||inRange(m,b2,b2+7))return{status:'break',anchor:'restroom',task:'Pausa breve'};return null}
function currentAgentState(id,now){const [open,close]=opsWindow(now);if(!inRange(now.mins,open,close))return{status:'off',anchor:AGENTS[id].home,task:'Fuera de horario'};return meetingState(id,now.mins,now)||lunchState(id,now.mins)||restroomState(id,now.mins,now)||{status:'working',anchor:AGENTS[id].home,task:workingTask(id)} }
function workingTask(id){return({sebas:'Revisando decisiones',facu:'Centralizando informes',chevy:'Analizando YouTube',vera:'Preparando contenido',nora:'Revisando TikTok SebasWit',luca:'Analizando DUAL / Nexus',iris:'Trabajando Instagram',echo:'Revisando Spotify',atlas:'Comparando plataformas',luz:'Organizando calendario'})[id]}
function statusLabel(s){return({working:'Trabajando',meeting:'En reunión',lunch:'Almorzando',break:'Pausa',off:'Fuera de horario'})[s]||s}function statusColor(s){return({working:'var(--green)',meeting:'var(--purple)',lunch:'var(--amber)',break:'var(--blue)',off:'#75849a'})[s]}
function getNotifications(){const raw=localStorage.getItem('sw_v10_notes');let notes=[];try{notes=raw?JSON.parse(raw):[]}catch{}const lim=Date.now()-10*86400000;return notes.filter(n=>new Date(n.date).getTime()>lim)}
function saveNotifications(notes){localStorage.setItem('sw_v10_notes',JSON.stringify(notes.slice(0,80)))}
function addNote(note){let notes=getNotifications();if(notes.some(n=>n.id===note.id))return;notes.unshift({...note,read:false,date:note.date||new Date().toISOString()});saveNotifications(notes)}
function buildNotes(){const d=new Date().toISOString().slice(0,10),yt=data.sectors.youtube.metrics,tm=data.sectors.tiktokMain.metrics,td=data.sectors.tiktokDual.metrics,ig=data.sectors.instagram.metrics;
 addNote({id:`${d}-yt-${yt.topVideoViews}`,sector:'YouTube',title:'Chevy reportó a Facu',message:`${yt.topVideo||'El contenido destacado'} es la señal principal. Recomendación: preparar una versión corta relacionada.`});
 addNote({id:`${d}-tiktok-${tm.periodViews}`,sector:'TikTok SebasWit',title:'Nora actualizó su informe',message:tm.periodViews<100?'La actividad reciente es baja. Conviene probar un clip más directo y breve.':'Hay una señal de actividad interesante. Conviene sostener el formato que mejor responde.'});
 addNote({id:`${d}-dual-${td.periodViews}`,sector:'TikTok DUAL',title:'Luca envió informe DUAL',message:'Mantener una narrativa serial y publicar piezas que continúen una historia, no clips aislados.'});
 addNote({id:`${d}-ig-${ig.followers}`,sector:'Instagram',title:'Iris informó a Facu',message:'Instagram Nexus sigue en etapa inicial. Prioridad: consistencia visual y Reels reutilizables.'});
 if(!data.sectors.spotify.metrics.connected)addNote({id:`${d}-spotify-pending`,sector:'Spotify',title:'Echo tiene una conexión pendiente',message:'El sector Spotify está listo, pero falta completar la API directa para traer datos ampliados.'});
}
function markNotesRead(){const notes=getNotifications().map(n=>({...n,read:true}));saveNotifications(notes)}
async function loadData(showToast=false){try{const r=await fetch(`/api/studio?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error();data=await r.json()}catch{data=structuredClone(DATA_FALLBACK)}buildNotes();render();if(showToast)toast('Datos actualizados')}
function render(){const now=arNow();const notes=getNotifications(),unread=notes.filter(n=>!n.read).length;states=Object.fromEntries(Object.keys(AGENTS).map(id=>[id,currentAgentState(id,now)]));const counts={working:0,meeting:0,lunch:0,break:0};Object.values(states).forEach(s=>{if(counts[s.status]!==undefined)counts[s.status]++});
 el('#app').innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="brandmark">SW</div><div><h1>SebasWeb Studios</h1><p>V10 Pro · empresa viva · datos + estrategia</p></div></div><div class="top-actions"><div class="chip hide-sm"><small>${now.date}</small><b>${String(now.h).padStart(2,'0')}:${String(now.m).padStart(2,'0')}</b></div><div class="chip hide-sm"><small>Datos</small><b>${data.source==='live'?'EN VIVO':'SEGURO'}</b></div><button class="icon-btn" id="refresh">↻ Actualizar</button><button class="icon-btn bell" id="bell">🔔 Facu${unread?`<span class="bell-count">${unread}</span>`:''}</button></div></header>
 <section class="summary"><div class="summary-card"><small>Trabajando</small><strong>${counts.working}</strong><p>en sus sectores</p></div><div class="summary-card"><small>En reunión</small><strong>${counts.meeting}</strong><p>revisando ideas</p></div><div class="summary-card"><small>Almuerzo</small><strong>${counts.lunch}</strong><p>turnos escalonados</p></div><div class="summary-card"><small>Pausa</small><strong>${counts.break}</strong><p>breve</p></div><div class="summary-card"><small>Avisos nuevos</small><strong>${unread}</strong><p>Facu centraliza</p></div></section>
 <div class="section-head"><div><h2>La empresa ahora</h2><p>Los NPC están separados del escenario. Se mueven entre puestos, reunión, comedor y baño según la jornada.</p></div><div class="live-legend"><span><i class="legend-dot working-dot"></i>Trabajando</span><span><i class="legend-dot meeting-dot"></i>Reunión</span><span><i class="legend-dot lunch-dot"></i>Almuerzo</span><span><i class="legend-dot break-dot"></i>Pausa</span></div></div>
 <section class="map-card"><div class="map-frame" id="map"><img class="map-bg" src="/studio-map.png" alt="Maqueta de SebasWeb Studios"><div class="map-tint"></div>${ROOM_HOTSPOTS.map(r=>`<button class="hotspot" data-room="${r.key}" style="left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%"><span class="hotspot-label">${esc(r.label)}</span></button>`).join('')}${Object.entries(AGENTS).map(([id,a])=>npcHtml(id,a,states[id])).join('')}</div><div class="activity-strip">${Object.entries(AGENTS).map(([id,a])=>`<div class="activity-pill"><b>${a.name}</b> · ${statusLabel(states[id].status)} · ${esc(states[id].task)}</div>`).join('')}</div></section>
 <div class="section-head"><div><h2>Informes por sector</h2><p>Cada sector analiza lo suyo; Facu concentra recomendaciones y las eleva a Dirección.</p></div></div><section class="sector-grid">${renderSectorCards()}</section></div><div id="overlayRoot"></div>`;
 el('#refresh').onclick=()=>loadData(true);el('#bell').onclick=openFacu;all('.hotspot').forEach(b=>b.onclick=()=>openRoom(b.dataset.room));all('.npc').forEach(b=>b.onclick=()=>openAgent(b.dataset.id));all('[data-sector]').forEach(b=>b.onclick=()=>openSector(b.dataset.sector));
 requestAnimationFrame(()=>requestAnimationFrame(()=>animateStates()));prevStates=structuredClone(states)
}
function npcHtml(id,a,s){const p=ANCHORS[s.anchor]||ANCHORS[a.home];return`<button class="npc ${s.status==='off'?'off':''}" data-id="${id}" style="left:${p.x}%;top:${p.y}%;--status-color:${statusColor(s.status)}" aria-label="${a.name}: ${statusLabel(s.status)}"><img src="${a.sprite}" alt="${a.name}"><span class="npc-tag">${a.name} · ${statusLabel(s.status)}</span></button>`}
function animateStates(){all('.npc').forEach(node=>{const id=node.dataset.id,s=states[id],old=prevStates[id];if(old&&old.anchor!==s.anchor){node.classList.add('moving');setTimeout(()=>node.classList.remove('moving'),2200)}})}
function metricPairs(key){const m=data.sectors[key]?.metrics||{};const defs={youtube:[['Suscriptores',m.subscribers],['Vistas canal',m.totalViews],['Vistas recientes',m.periodViews],['Top video',m.topVideo]],tiktokMain:[['Seguidores',m.followers],['Likes',m.totalLikes],['Videos',m.videos],['Vistas recientes',m.periodViews]],tiktokDual:[['Seguidores',m.followers],['Likes',m.totalLikes],['Videos',m.videos],['Vistas recientes',m.periodViews]],instagram:[['Cuenta',m.account],['Seguidores',m.followers],['Posts',m.mediaCount],['Alcance',m.reach]],spotify:[['Artista',m.artist],['Conectado',m.connected?'Sí':'Pendiente'],['Seguidores',m.followers??'-'],['Lanzamientos',m.releases??'-']],strategy:[['Estado','Activo'],['Cruce','Multiplataforma'],['Prioridad','Hoy'],['Agente','Atlas']],publishing:[['Estado','Activo'],['Calendario','En revisión'],['Aprobaciones','Dirección'],['Agente','Luz']]};return defs[key]||[]}
function renderSectorCards(){const keys=['youtube','tiktokMain','tiktokDual','instagram','spotify','strategy','publishing'];return keys.map(k=>{const s=data.sectors[k];return`<article class="sector-card"><div class="sector-head"><div><h3>${esc(s.title)}</h3><p>${esc(s.agent)} · análisis del sector</p></div><span class="mode-badge">${data.source==='live'?'en vivo':'modo seguro'}</span></div><div class="metrics">${metricPairs(k).map(([l,v])=>`<div class="metric"><span>${esc(l)}</span><strong>${typeof v==='number'?fmt(v):esc(v??'-')}</strong></div>`).join('')}</div><div class="card-actions"><button class="btn primary" data-sector="${k}">Ver informe</button></div></article>`}).join('')}
function openOverlay(content){el('#overlayRoot').innerHTML=`<div class="overlay" id="overlay"><aside class="drawer">${content}</aside></div>`;el('#overlay').onclick=e=>{if(e.target.id==='overlay')closeOverlay()};el('#close')?.addEventListener('click',closeOverlay)}function closeOverlay(){el('#overlayRoot').innerHTML=''}
function openAgent(id){const a=AGENTS[id],s=states[id];openOverlay(`<div class="drawer-top"><div><h2>${a.name}</h2><p class="subtitle">${esc(a.role)}</p></div><button id="close" class="close">×</button></div><div class="block agent-hero"><img src="${a.sprite}" alt="${a.name}"><div><div class="status-line"><i style="background:${statusColor(s.status)}"></i>${statusLabel(s.status)}</div><h4>${esc(s.task)}</h4><p>${agentInsight(id)}</p></div></div>${a.sector&&data.sectors[a.sector]?`<button class="btn primary" id="sectorFromAgent">Abrir informe de su sector</button>`:''}`);if(el('#sectorFromAgent'))el('#sectorFromAgent').onclick=()=>openSector(a.sector)}
function agentInsight(id){return({sebas:'Recibe el resumen ejecutivo de Facu y toma las decisiones finales.',facu:'Recibe informes de todos los sectores, los ordena por prioridad y te los presenta como notificaciones.',chevy:'Analiza YouTube: vistas, retención y señales de rendimiento.',vera:'Convierte las señales de YouTube en ideas de contenido y piezas reutilizables.',nora:'Observa TikTok SebasWit y propone formatos cortos para música.',luca:'Gestiona la lectura de TikTok DUAL / Nexus y su continuidad narrativa.',iris:'Revisa Instagram y la coherencia visual del universo Nexus.',echo:'Centraliza Spotify y la información musical disponible.',atlas:'Cruza datos de plataformas y convoca reuniones cuando encuentra una oportunidad.',luz:'Convierte decisiones en calendario, publicaciones y seguimiento.'})[id]}
function openRoom(room){const mapping={direction:'strategy',coordination:'strategy',youtube:'youtube',tiktokMain:'tiktokMain',tiktokDual:'tiktokDual',instagram:'instagram',spotify:'spotify',strategy:'strategy',publishing:'publishing'};if(mapping[room])return openSector(mapping[room]);const labels={meeting:'Sala de reuniones',lunch:'Comedor / café',restroom:'Baño'};openOverlay(`<div class="drawer-top"><div><h2>${labels[room]}</h2><p class="subtitle">Área común</p></div><button id="close" class="close">×</button></div><div class="block"><p>${room==='meeting'?'Los agentes vienen acá solo durante reuniones programadas y luego vuelven a su puesto.':room==='lunch'?'El almuerzo está dividido en turnos para que la empresa siga operativa.':'Las pausas son breves y se calculan de forma determinista durante la jornada.'}</p></div>`)}
function sectorRecommendation(key){const m=data.sectors[key]?.metrics||{};if(key==='youtube')return`Chevy y Vera: priorizar ${m.topVideo||'el contenido con mejor retención'} y probar un recorte vertical de entrada rápida.`;if(key==='tiktokMain')return m.periodViews<100?'Nora: aumentar la frecuencia de pruebas con clips más directos, evitando repetir exactamente el mismo montaje.':'Nora: sostener el formato con mejor señal y crear una segunda pieza relacionada.';if(key==='tiktokDual')return'Luca: reforzar continuidad entre clips y cerrar cada pieza con una pequeña promesa narrativa.';if(key==='instagram')return'Iris: mantener una estética reconocible y alimentar Reels con material que ya funciona en video corto.';if(key==='spotify')return m.connected?'Echo: destacar los lanzamientos que mejor representen la etapa actual.':'Echo: completar la conexión directa de Spotify para enriquecer el informe musical.';if(key==='strategy')return'Atlas: cruzar señales entre YouTube, TikTok y DUAL antes de proponer nuevas piezas.';return'Luz: convertir las decisiones aprobadas en calendario y dejar visible qué está pendiente de Sebas.'}
function openSector(key){const s=data.sectors[key];if(!s)return;openOverlay(`<div class="drawer-top"><div><h2>${esc(s.title)}</h2><p class="subtitle">Informe de ${esc(s.agent)}</p></div><button id="close" class="close">×</button></div><div class="metrics">${metricPairs(key).map(([l,v])=>`<div class="metric"><span>${esc(l)}</span><strong>${typeof v==='number'?fmt(v):esc(v??'-')}</strong></div>`).join('')}</div><div class="block"><h4>Lectura del sector</h4><p>${esc(sectorRecommendation(key))}</p></div><div class="block"><h4>Flujo</h4><p>El informe se envía a Facu. Si requiere una decisión, aparece en tu campanita de Dirección.</p></div>`)}
function openFacu(){markNotesRead();const notes=getNotifications();openOverlay(`<div class="drawer-top"><div><h2>Centro Facu</h2><p class="subtitle">Coordinación · notificaciones · resumen para Dirección</p></div><button id="close" class="close">×</button></div><div class="block"><h4>Últimas notificaciones</h4>${notes.length?notes.map(n=>`<div class="note ${n.read?'':'unread'}"><small>${esc(n.sector)} · ${new Date(n.date).toLocaleString('es-AR')}</small><b>${esc(n.title)}</b><p>${esc(n.message)}</p></div>`).join(''):'<p>No hay avisos.</p>'}</div><div class="block"><h4>Consultar a Facu</h4><p>Podés preguntar por YouTube, TikTok, DUAL, Instagram, Spotify o qué priorizar hoy.</p><div class="question"><input id="facuQ" placeholder="¿Qué está pasando hoy?"><button class="btn primary" id="ask">Preguntar</button></div><div id="answer"></div></div>`);el('#ask').onclick=answerFacu;el('#facuQ').onkeydown=e=>{if(e.key==='Enter')answerFacu()}}
function answerFacu(){const q=(el('#facuQ').value||'').toLowerCase();let a='Hoy priorizaría las señales de YouTube, mantenería pruebas cortas en TikTok y separaría la narrativa de DUAL del contenido musical.';if(q.includes('youtube'))a=sectorRecommendation('youtube');else if(q.includes('dual'))a=sectorRecommendation('tiktokDual');else if(q.includes('tiktok'))a=sectorRecommendation('tiktokMain');else if(q.includes('instagram'))a=sectorRecommendation('instagram');else if(q.includes('spotify'))a=sectorRecommendation('spotify');else if(q.includes('quién')||q.includes('trabaj')){const on=Object.entries(states).filter(([,s])=>s.status==='working').map(([id])=>AGENTS[id].name);a=`Ahora están trabajando: ${on.join(', ')||'nadie'}.`}el('#answer').innerHTML=`<div class="answer">${esc(a)}</div>`}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function tick(){const now=arNow(),next={};Object.keys(AGENTS).forEach(id=>next[id]=currentAgentState(id,now));let changed=false;Object.keys(next).forEach(id=>{if(!states[id]||states[id].anchor!==next[id].anchor||states[id].status!==next[id].status)changed=true});if(changed){prevStates=structuredClone(states);states=next;Object.entries(states).forEach(([id,s])=>{const node=document.querySelector(`.npc[data-id="${id}"]`);if(!node)return;const p=ANCHORS[s.anchor]||ANCHORS[AGENTS[id].home];node.style.left=p.x+'%';node.style.top=p.y+'%';node.style.setProperty('--status-color',statusColor(s.status));node.classList.toggle('off',s.status==='off');node.classList.add('moving');setTimeout(()=>node.classList.remove('moving'),2200);node.querySelector('.npc-tag').textContent=`${AGENTS[id].name} · ${statusLabel(s.status)}`});}}
window.addEventListener('DOMContentLoaded',()=>{loadData(false);timer=setInterval(tick,30000);setInterval(()=>loadData(false),120000)})
