const SNAPSHOT = {
  source:"snapshot",updatedAt:"2026-09-20T16:37:00.000Z",
  company:{name:"SebasWeb Studios",director:"Sebas",activeAgents:4,totalAgents:5},
  youtube:{subscribers:2680,totalViews:126293,videos:77,periodViews:119,periodLikes:2,topVideo:"LA BRUJA 🔮 Lunes 21 de Septiembre",topVideoViews:85,topRetention:111.23},
  tiktok:{followers:1108,totalLikes:17580,videos:21,periodViews:50,periodLikes:2,profileViews:1}
};
const ROOM_INFO={youtube:{title:"YouTube Lab",icon:"▶",subtitle:"Retención · Shorts · crecimiento"},tiktok:{title:"TikTok Room",icon:"♪",subtitle:"Alcance · actividad · señales"},strategy:{title:"Sala de Estrategia",icon:"✦",subtitle:"Cruce de plataformas"},publishing:{title:"Publishing Desk",icon:"↗",subtitle:"Aprobaciones · calendario"}};
let studioData=null;let selectedId=null;let refreshing=false;
const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const num=n=>Number.isFinite(Number(n))?Number(n):0;const fmt=n=>num(n).toLocaleString("es-AR");const compact=n=>new Intl.NumberFormat("es-AR",{notation:"compact",maximumFractionDigits:1}).format(num(n));
function makeAgents(d){const yt=d.youtube;const tt=d.tiktok;return[
{id:"yt-scout",name:"Milo",role:"YouTube Analytics",room:"youtube",status:"working",task:yt.topVideoViews?`Midiendo el impulso de “${yt.topVideo.slice(0,34)}${yt.topVideo.length>34?"…":""}”`:"Revisando el rendimiento reciente",accent:"#ff4e66",metrics:[{label:"Suscriptores",value:fmt(yt.subscribers)},{label:"Vistas canal",value:fmt(yt.totalViews)},{label:"Vistas 30 días",value:fmt(yt.periodViews)},{label:"Videos",value:fmt(yt.videos)}],insight:yt.topVideoViews?`El contenido con más movimiento del período es “${yt.topVideo}” con ${fmt(yt.topVideoViews)} vistas.`:"Todavía no hay suficiente actividad reciente para destacar una pieza."},
{id:"yt-content",name:"Vera",role:"YouTube Content",room:"youtube",status:"watching",task:"Buscando señales de retención y piezas para recortar",accent:"#f7b955",metrics:[{label:"Mejor retención",value:`${num(yt.topRetention).toFixed(1)}%`,note:yt.topRetention>100?"Puede incluir repeticiones/loops":""},{label:"Likes 30 días",value:fmt(yt.periodLikes)},{label:"Top pieza",value:`${fmt(yt.topVideoViews)} vistas`}],insight:yt.topRetention>=70?"Hay una señal fuerte de retención en la mejor pieza reciente. Conviene reutilizar ese arranque o formato en próximos Shorts.":"La prioridad es probar aperturas más rápidas y medir qué primeros segundos retienen mejor."},
{id:"tt-scout",name:"Nora",role:"TikTok Analytics",room:"tiktok",status:"working",task:"Leyendo crecimiento, visualizaciones y actividad de perfil",accent:"#6df4e7",metrics:[{label:"Seguidores",value:fmt(tt.followers)},{label:"Likes totales",value:fmt(tt.totalLikes)},{label:"Vistas 30 días",value:fmt(tt.periodViews)},{label:"Videos",value:fmt(tt.videos)}],insight:tt.periodViews?`TikTok registró ${fmt(tt.periodViews)} vistas en el período disponible. Nora vigila cualquier aceleración para marcarla en la sala de estrategia.`:"TikTok está conectado, pero todavía no entrega actividad suficiente en el período consultado."},
{id:"cross-strategy",name:"Atlas",role:"Cross-platform Strategy",room:"strategy",status:"working",task:"Comparando YouTube y TikTok para detectar qué reutilizar",accent:"#9f8cff",metrics:[{label:"YouTube 30d",value:`${fmt(yt.periodViews)} vistas`},{label:"TikTok 30d",value:`${fmt(tt.periodViews)} vistas`},{label:"Agentes activos",value:"4 / 5"}],insight:yt.periodViews>=tt.periodViews?"YouTube muestra más actividad en la ventana consultada. Atlas prioriza detectar qué pieza puede viajar a TikTok sin copiarla literalmente.":"TikTok muestra más actividad en la ventana consultada. Atlas busca qué concepto conviene convertir en Short de YouTube."},
{id:"publisher",name:"Luz",role:"Publishing Desk",room:"publishing",status:"waiting",task:"Esperando conexión operativa de Metricool",accent:"#63d98a",metrics:[{label:"Cola",value:"Sincronización pendiente"},{label:"YouTube",value:"Lectura activa"},{label:"TikTok",value:"Lectura activa"}],insight:"Cuando conectemos la capa de publicación, esta mesa va a mostrar borradores, aprobaciones y publicaciones programadas."}
]}
function enrich(d){d.agents=makeAgents(d);d.executive=[];if(d.youtube.topVideoViews)d.executive.push(`YouTube: “${d.youtube.topVideo}” lidera el período con ${fmt(d.youtube.topVideoViews)} vistas.`);if(d.youtube.topRetention>=70)d.executive.push(`Retención: la mejor pieza reciente marca ${num(d.youtube.topRetention).toFixed(1)}%, una señal para estudiar su apertura.`);d.executive.push(`TikTok: ${fmt(d.tiktok.followers)} seguidores y ${fmt(d.tiktok.totalLikes)} likes acumulados.`);d.executive.push("Publishing: Metricool todavía no está conectado a esta oficina, por eso Luz está en espera.");return d}
function person(a){return `<button class="agent-person ${a.status}" data-agent="${a.id}" aria-label="Abrir ${esc(a.name)}"><span class="agent-bubble">${a.status==="waiting"?"…":a.status==="watching"?"◎":"⚡"}</span><span class="person-shadow"></span><span class="person" style="--agent:${a.accent}"><span class="hair"></span><span class="head"><span class="face-dot left"></span><span class="face-dot right"></span></span><span class="body"></span><span class="arm a1"></span><span class="arm a2"></span><span class="leg l1"></span><span class="leg l2"></span></span><span class="agent-name">${esc(a.name)}</span><span class="agent-role">${esc(a.role)}</span></button>`}
function desk(room,second=false){const tone=room==="youtube"?"red":room==="tiktok"?"cyan":room==="publishing"?"green":"purple";return `<div class="desk ${tone}${second?" second":""}"><div class="screen"><span></span><span></span><span></span></div><div class="keyboard"></div>${second?"":"<div class=\"mug\"></div>"}</div>`}
function room(room,agents){const r=ROOM_INFO[room];return `<section class="room room-${room}"><div class="room-header"><div><span class="room-icon">${r.icon}</span><h2>${r.title}</h2></div><span class="room-count">${agents.filter(a=>a.status!=="waiting").length} activos</span></div><p class="room-subtitle">${r.subtitle}</p><div class="room-floor-lines"></div><div class="plant"><span></span><i></i></div>${desk(room)}${agents.length>1?desk(room,true):""}<div class="agents-row">${agents.map(person).join("")}</div></section>`}
function render(){const d=studioData;const updated=new Date(d.updatedAt);const rooms={youtube:d.agents.filter(a=>a.room==="youtube"),tiktok:d.agents.filter(a=>a.room==="tiktok"),strategy:d.agents.filter(a=>a.room==="strategy"),publishing:d.agents.filter(a=>a.room==="publishing")};const working=d.agents.filter(a=>a.status!=="waiting").length;document.getElementById("app").innerHTML=`<main class="studio-shell"><header class="topbar"><div class="brand"><div class="brand-mark">SW</div><div><b>SEBASWEB</b><span>STUDIOS</span></div></div><div class="top-actions"><div class="source-badge ${d.source}"><i></i>${d.source==="live"?"DATOS EN VIVO":"SNAPSHOT SEGURO"}</div><button class="refresh" id="refreshBtn">↻ Actualizar</button><div class="director-chip"><span>S</span><div><small>DIRECTOR GENERAL</small><b>Sebas</b></div></div></div></header><section class="command-strip"><div><small>OFICINA ACTIVA</small><strong>${working}<span> / ${d.company.totalAgents}</span></strong><p>agentes trabajando ahora</p></div><div><small>YOUTUBE</small><strong>${compact(d.youtube.subscribers)}</strong><p>suscriptores</p></div><div><small>TIKTOK</small><strong>${compact(d.tiktok.followers)}</strong><p>seguidores</p></div><div class="updated"><small>ÚLTIMA SINCRONIZACIÓN</small><strong>${updated.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</strong><p>${updated.toLocaleDateString("es-AR",{day:"2-digit",month:"short"})}</p></div></section><section class="office-wrap"><div class="office-title"><div><span class="eyebrow">PLANTA PRINCIPAL</span><h1>Centro de Operaciones</h1><p>Tocá cualquier agente para abrir su escritorio y sus métricas.</p></div><div class="live-dot"><i></i> oficina online</div></div><div class="office-grid">${room("youtube",rooms.youtube)}${room("tiktok",rooms.tiktok)}${room("strategy",rooms.strategy)}${room("publishing",rooms.publishing)}<section class="director-room"><div class="director-glow"></div><div class="director-sign">DIRECCIÓN GENERAL</div><div class="director-desk"><div class="director-monitor">SW</div><div class="desk-edge"></div></div><div class="director-person"><span class="director-head">S</span><strong>SEBAS</strong><small>Productor · Director General</small></div></section></div></section><section class="executive-panel"><div class="executive-heading"><div><span class="eyebrow">BRIEF DEL DIRECTOR</span><h2>Qué está pasando ahora</h2></div><span class="ai-chip">✦ auto-análisis</span></div><div class="brief-grid">${d.executive.map((x,i)=>`<div class="brief"><span>${String(i+1).padStart(2,"0")}</span><p>${esc(x)}</p></div>`).join("")}</div></section><footer><span>SEBASWEB STUDIOS · CONTROL ROOM</span><span>Actualización automática cada 2 minutos</span></footer><div id="drawerRoot"></div></main>`;document.querySelectorAll("[data-agent]").forEach(el=>el.addEventListener("click",()=>openAgent(el.dataset.agent)));$("#refreshBtn").addEventListener("click",()=>refresh(false))}
function openAgent(id){selectedId=id;const a=studioData.agents.find(x=>x.id===id);if(!a)return;const state=a.status==="working"?"Trabajando":a.status==="watching"?"Vigilando":"En espera";$("#drawerRoot").innerHTML=`<div class="drawer-backdrop" id="backdrop"><aside class="drawer"><button class="close" id="closeDrawer">×</button><div class="drawer-agent" style="--accent:${a.accent}"><div class="drawer-avatar">${esc(a.name[0])}</div><div><span class="status-pill ${a.status}">${state}</span><h3>${esc(a.name)}</h3><p>${esc(a.role)}</p></div></div><div class="task-box"><small>TAREA ACTUAL</small><strong>${esc(a.task)}</strong></div><div class="metrics-grid">${a.metrics.map(m=>`<div class="metric"><span>${esc(m.label)}</span><strong>${esc(m.value)}</strong>${m.note?`<small>${esc(m.note)}</small>`:""}</div>`).join("")}</div><div class="insight"><span>✦ INFORME DEL AGENTE</span><p>${esc(a.insight)}</p></div></aside></div>`;$("#closeDrawer").onclick=closeAgent;$("#backdrop").onclick=e=>{if(e.target.id==="backdrop")closeAgent()}}
function closeAgent(){selectedId=null;$("#drawerRoot").innerHTML=""}
function toast(msg){const old=$(".toast");if(old)old.remove();const el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
async function refresh(silent=true){if(refreshing)return;refreshing=true;const btn=$("#refreshBtn");if(btn){btn.disabled=true;btn.textContent="Actualizando…"}try{const r=await fetch(`/api/studio?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("api");const d=await r.json();studioData=enrich(d);render();if(selectedId)openAgent(selectedId);if(!silent)toast(d.source==="live"?"Datos actualizados desde Windsor.ai":"Usando snapshot segura") }catch(e){if(!studioData){studioData=enrich(structuredClone(SNAPSHOT));render()}if(!silent)toast("No hubo conexión: mantengo la última información disponible") }finally{refreshing=false;const b=$("#refreshBtn");if(b){b.disabled=false;b.textContent="↻ Actualizar"}}}
window.addEventListener("DOMContentLoaded",()=>{studioData=enrich(structuredClone(SNAPSHOT));render();refresh(true);setInterval(()=>refresh(true),120000)});
